# Generated by Django 4.0 on 2021-12-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(max_length=120, null=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
