# Generated by Django 4.0 on 2021-12-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateposted',
            field=models.DateField(null=True),
        ),
    ]
