# Generated by Django 4.0 on 2022-01-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_product_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=120, null=True)),
                ('quantity', models.IntegerField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('buyer', models.CharField(blank=True, max_length=120, null=True)),
                ('town', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=120, null=True)),
                ('total', models.IntegerField(blank=True, max_length=120, null=True)),
                ('dateposted', models.DateField(null=True)),
            ],
        ),
    ]
