# Generated by Django 4.0 on 2022-02-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile', models.IntegerField(blank=True, max_length=120, null=True)),
                ('town', models.CharField(blank=True, max_length=120, null=True)),
                ('dateordered', models.DateField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dateposted',
            new_name='dateordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='town',
        ),
    ]
