# Generated by Django 4.0 on 2022-02-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_customer_rename_dateposted_order_dateordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=120, null=True),
        ),
    ]
